name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *' # runs every 2 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Insert Token
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml

      - name: Download latest Stockfish dev 
        run: |
          curl -L -o stockfish.zip http://abrok.eu/stockfish/latest/linux/stockfish_x64_modern.zip
          unzip -o stockfish.zip -d engines/
          mv engines/stockfish* engines/stockfish
          chmod +x engines/stockfish

      - name: Download Stockfish 17.1 for Chess960
        run: |
          curl -L -o engines/newsf https://github.com/MaggiCoder16/maggibot_backup/releases/download/sf17/newsf
          chmod +x engines/newsf

      - name: Make Fairy Stockfish Executable
        run: |
          chmod +x engines/fairy-stockfish
      
      - name: Run Bot
        run: python -u user_interface.py 
